Repository nunocoracao/blowfish, pull requests merged in 2022-10, with the labels that each got.

#73 fixed js bug on copy code module
  assets/js/code.js
Labels: bug

#75 added instructions and icons to menu entries
  exampleSite/config/_default/menus.en.toml
  exampleSite/content/docs/getting-started/index.md
  layouts/partials/header/basic.html
  package.json
Labels: enhancement

#87 make external links open by default on a new tab
  layouts/_default/_markup/render-link.html
Labels: enhancement

#96 Add pl.yaml Polish Translation
  i18n/pl.yaml
Labels: enhancement

#131 hr.yaml
  i18n/hr.yaml
Labels: documentation, enhancement

#129 Optionally disable footer menu. Enabled by default
  config/_default/params.toml
  exampleSite/content/docs/configuration/index.md
  layouts/partials/footer.html
Labels: documentation, enhancement
